![rmotr](https://i.imgur.com/jiPp4hj.png)
<hr style="margin-bottom: 40px;">

# Numpy additional exercises
![separator2](https://i.imgur.com/4gX5WFr.png)

In [2]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.14.5


![separator1](https://i.imgur.com/ZUWYTii.png)

## Array creation

In [5]:
# Create a numpy array of size 10, filled with zeros.
np.zeros((10), dtype = int)
# Your code goes here

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# Create a numpy array with values ranging from 10 to 49
np.random.randint(10, 49, size = 10)
# Your code goes here

array([16, 11, 35, 41, 10, 29, 46, 24, 22, 37])

In [10]:
# Create a numpy matrix of 2*2 integers, filled with ones.
np.ones((2,2), dtype= int)
# Your code goes here

array([[1, 1],
       [1, 1]])

In [11]:
# Create a numpy matrix of 3*2 float numbers, filled with ones.
np.ones((3,2), dtype = float)
# Your code goes here

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.
X = np.arange(4, dtype=np.int)
Y = np.full_like(X, 1)
# Your code goes here

In [27]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)
Y = np.full_like(X,0)
# Your code goes here

In [32]:
# Create a numpy matrix of 4*4 integers, filled with fives.
X = np.full((4,4),5,dtype = int)
# Your code goes here

In [36]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
X = np.array([[2,3], [6,2]], dtype=np.int)
Y = np.full_like(X,5)
# Your code goes here

In [39]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
X = np.identity(3, dtype = int)
# Your code goes here

In [50]:
# Create a numpy array, filled with 3 random integer values between 1 and 10
np.random.randint(1, 10, size = 3)
# Your code goes here

array([3, 2, 2])

In [52]:
# Create a 3*3*3 numpy matrix, filled with random float values
np.random.rand(3,3,3)
# Your code goes here

array([[[0.01363382, 0.41927637, 0.87140595],
        [0.67715212, 0.08863827, 0.64784782],
        [0.95793664, 0.46156196, 0.41524333]],

       [[0.12669758, 0.7972458 , 0.64823021],
        [0.80077132, 0.5279374 , 0.61087641],
        [0.94875712, 0.02614174, 0.41348116]],

       [[0.79309916, 0.11052879, 0.58145378],
        [0.2597075 , 0.16095961, 0.39236458],
        [0.45225381, 0.56567121, 0.92177028]]])

In [57]:
# Given the X python list convert it to an Y numpy array
X = [1, 2, 3]
print(X, type(X))
Y = np.asarray(X)
print(Y, type(Y))
# Your code goes here

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [59]:
# Given the X numpy array, make a copy and store it on Y.
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))
Y = np.copy(X)
print(Y, id(Y))
# Your code goes here

[5 2 3] 140124212409408
[5 2 3] 140124212349008


In [63]:
# Create a numpy array with numbers from 1 to 10
np.arange(1,10)
# Your code goes here

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Create a numpy array with the odd numbers between 1 to 10
a = np.arange(1, 10)
a = a[a%2!=0]
# Your code goes here

In [69]:
# Create a numpy array with numbers from 1 to 10, in descending order.
np.arange(10,1,-1)
# Your code goes here

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [3]:
# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8
np.arange(9).reshape((3, 3))
# Your code goes here

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
# Show the memory size of the given Z numpy matrix
Z = np.zeros((10,10))
Z.nbytes
# Your code goes here

800

![separator1](https://i.imgur.com/ZUWYTii.png)

## Array indexation

In [6]:
# Given the X numpy array, show it's first element
X = np.array(['A','B','C','D','E'])
X[0]
# Your code goes here

'A'

In [7]:
# Given the X numpy array, show it's last element
X = np.array(['A','B','C','D','E'])
X[-1]
# Your code goes here

'E'

In [10]:
# Given the X numpy array, show it's first three elements
X = np.array(['A','B','C','D','E'])
X[:3]
# Your code goes here

array(['A', 'B', 'C'], dtype='<U1')

In [12]:
# Given the X numpy array, show all middle elements
X = np.array(['A','B','C','D','E'])
X[1:-1]
# Your code goes here

array(['B', 'C', 'D'], dtype='<U1')

In [14]:
# Given the X numpy array, show the elements in reverse position
X = np.array(['A','B','C','D','E'])
X[-1::-1]
# Your code goes here

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [20]:
# Given the X numpy array, show the elements in an odd position
X = np.array(['A','B','C','D','E'])
X[1::2]
# Your code goes here

array(['B', 'D'], dtype='<U1')

In [22]:
# Given the X numpy matrix, show the first row elements
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
X[0]

array([1, 2, 3, 4])

In [23]:
# Given the X numpy matrix, show the last row elements
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
X[-1]

array([13, 14, 15, 16])

In [24]:
# Given the X numpy matrix, show the first element on first row
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
X[0][0]

1

In [25]:
# Given the X numpy matrix, show the last element on last row
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
X[-1][-1]

16

In [26]:
# Given the X numpy matrix, show the middle row elements
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
X[1:-1]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
# Given the X numpy matrix, show the first two elements on the first two rows
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
# [i[:2] for i in X[:2]]
X[:2,:2]

array([[1, 2],
       [5, 6]])

In [83]:
# Given the X numpy matrix, show the last two elements on the last two rows
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
#[i[-2:] for i in X[-2:]]
X[-2:,-2:]

array([[11, 12],
       [15, 16]])

![separator1](https://i.imgur.com/ZUWYTii.png)

## Array manipulation

In [59]:
# Convert the given integer numpy array to float
X = np.array([-5, -3, 0, 10, 40])

# Your code goes here
X.astype(float)

array([-5., -3.,  0., 10., 40.])

In [60]:
# Reverse the given numpy array (first element becomes last)
X = np.array([-5, -3, 0, 10, 40])

# Your code goes here
X[-1::-1]

array([40, 10,  0, -3, -5])

In [65]:
# Order (sort) the given numpy array
X = np.array([0, 10, -5, 40, -3])

# Your code goes here
X.sort()
X

array([-5, -3,  0, 10, 40])

In [68]:
# Given the X numpy array, set the fifth element equal to 1
X = np.zeros(10)

# Your code goes here
X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [72]:
# Given the X numpy array, change the 50 with a 40
X = np.array([10, 20, 30, 50])

# Your code goes here
X[X == 50] = 40
X

array([10, 20, 30, 40])

In [74]:
# Given the X numpy matrix, change the last row with all 1
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
X[-1] = 1
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [80]:
# Given the X numpy matrix, change the last item on the last row with a 0
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
X[-1,(-1)] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [88]:
# Given the X numpy matrix, add 5 to every element
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
X += 5
X

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

![separator1](https://i.imgur.com/ZUWYTii.png)

## Boolean arrays _(also called masks)_

In [90]:
# Given the X numpy array, make a mask showing negative elements
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

# Your code goes here
X < 0

array([ True, False, False,  True, False, False, False, False,  True,
       False])

In [91]:
# Given the X numpy array, get the negative elements
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

# Your code goes here
X[X < 0]

array([-1, -4, -9])

In [92]:
# Given the X numpy array, get numbers higher than 5
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

# Your code goes here
X[X > 5]

array([ 6, 10])

In [93]:
# Given the X numpy array, get numbers higher than the elements mean
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

# Your code goes here
X[X > X.mean()]

array([ 2,  5,  6, 10])

In [95]:
# Given the X numpy array, get numbers equal to 2 or 10
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

# Your code goes here
X[(X == 2) | (X == 10)]

array([ 2, 10])

![separator1](https://i.imgur.com/ZUWYTii.png)

## Logic functions

In [101]:
# Given the X numpy array, return True if none of its elements is zero
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

# Your code goes here
all(X == 0)

False

In [100]:
# Given the X numpy array, return True if any of its elements is zero
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

# Your code goes here
any(X == 0)

True

![separator1](https://i.imgur.com/ZUWYTii.png)

## Summary statistics

In [102]:
# Given the X numpy array, show the sum of its elements
X = np.array([3,5,6,7,2,3,4,9,4])

# Your code goes here
X.size

9

In [105]:
# Given the X numpy array, show the mean value of its elements
X = np.array([1,2,0,4,5,6,0,0,9,10])

# Your code goes here
X.mean()

3.7

In [108]:
# Given the X numpy matrix, show the sum of its columns
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
np.sum(X, axis = 0)

array([28, 32, 36, 40])

In [109]:
# Given the X numpy matrix, show the mean value of its rows
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# Your code goes here
np.mean(X, axis = 1)

array([ 2.5,  6.5, 10.5, 14.5])

In [110]:
# Given the X numpy array, show the max value of its elements
X = np.array([1,2,0,4,5,6,0,0,9,10])

# Your code goes here
np.amax(X)

10

![separator2](https://i.imgur.com/4gX5WFr.png)